In [10]:
#1Write a program to create a 5 dimensional array with all zeros and ones
import numpy as np

In [11]:
x=np.array([[[[[1,0,0],[1,1,0],[1,0,1]]]]])

In [12]:
x

array([[[[[1, 0, 0],
          [1, 1, 0],
          [1, 0, 1]]]]])

In [14]:
x.ndim

5

In [26]:
#Write a program to create an array of 10 zeros,10 ones, and 10 fives in row 1 2 and 3 which create a new array of shape (3,10)

import numpy as np

In [27]:
x=np.zeros(10,)
y=np.ones(10,)
z=np.full(10,5)

In [28]:
u=np.array([x,y,z])

In [29]:
u

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.]])

In [30]:
u.shape

(3, 10)

In [33]:
#3 Write a program to create a 3x4 matrix filled with values from 10 to 21.

x1=np.arange(10,22).reshape(3,4)

In [34]:
x1

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

In [35]:
#4) Write a  program to create a 10x10 zero matrix with elements on the main diagonal equal to 0,1,2,3,4,5,6,7,8,9

x=np.diag((0,1,2,3,4,5,6,7,8,9))

In [36]:
x

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 2, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 3, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 4, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 5, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 6, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 7, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 8, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 9]])

In [39]:
#5)Write a program to create a 4x4 array. Create an array from below array by swapping first and last, second and 
#third columns.

x=np.arange(1,17).reshape(4,4)

In [40]:
x

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [41]:
x[::,::-1]

array([[ 4,  3,  2,  1],
       [ 8,  7,  6,  5],
       [12, 11, 10,  9],
       [16, 15, 14, 13]])

In [42]:
#6) Write a program to reverse an array (the first element becomes the last).
#Given array:[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 ]


x=np.arange(12,28)

In [43]:
x

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27])

In [44]:
x[::-1]

array([27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12])

In [ ]:
# Write a program to access all the elements greater than 30 and less than 80 and multiples of 5 from an 
#array of shape 10,10 .Elements range from 1 to 100



In [68]:
#Write a program to create a 2D array with 1 on the border and 0 inside.

x=np.ones((5,5),dtype=int)
x[1:-1,1:-1]=0

In [69]:
x

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

In [66]:
#Write a program to create a checkerboard pattern .Don't use default array function

x=np.ones((8,8),dtype=int)
x
x[1::2,::2]=0
x[::2,1::2]=0

In [67]:
x

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

In [57]:
#11Write a program to find common values between two arrays.

x=np.arange(0,9).reshape(3,3)

In [58]:
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [59]:
x.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
#Write a user defined function for creating a 1 or 2d array from scratch without using array functions