In [1]:
import numpy as np

In [25]:
u=np.genfromtxt(r"C:\Users\DELL\Downloads\tipsf.csv",delimiter=",",skip_header=1)

In [26]:
u

array([[  0.  ,  16.99,   1.01, ...,   1.  ,   0.  ,   2.  ],
       [  1.  ,  10.34,   1.66, ...,   1.  ,   0.  ,   3.  ],
       [  2.  ,  21.01,   3.5 , ...,   1.  ,   0.  ,   3.  ],
       ...,
       [241.  ,  22.67,   2.  , ...,   0.  ,   0.  ,   2.  ],
       [242.  ,  17.82,   1.75, ...,   0.  ,   0.  ,   2.  ],
       [243.  ,  18.78,   3.  , ...,   2.  ,   0.  ,   2.  ]])

In [5]:
# 1 what is total bill value
np.sum(u[:,1])

4827.77

In [6]:
#2 what is total tip value
np.sum(u[:,2])

731.5799999999999

In [8]:
#3 count how many sun,sat,thu,fri are these
x1=np.unique(u[:,5],return_counts=True)
b,s=x1
y=0
for i in b:
    if(i==0):
        print("sun = ",s[y])
        y+=1
    elif(i==1):
        print("sat = ",s[y])
        y+=1
    elif(i==2):
        print("thu = ",s[y])
        y+=1
    else:
        print("fri = ",s[y])
        y+=1 

sun =  87
sat =  76
thu =  62
fri =  19


In [9]:
# how many smokers are these
np.sum(u[:,4])

93.0

In [10]:
#what is avg tip given by female and male
a1=np.sum(u[:,2].take(np.where(u[:,3]==0)))
a2=np.sum(u[:,2].take(np.where(u[:,3]==1)))
x=np.unique(u[:,3],return_counts=True)
d,z=x
print(a1/z[0],"avg tip by female")
print(a1/z[1],"avg tip by male")


2.8334482758620685 avg tip by female
1.5701273885350315 avg tip by male


In [12]:
#6) How much amount have been spent by female and male
a1=np.sum(u[:,1].take(np.where(u[:,3]==0)))
a2=np.sum(u[:,1].take(np.where(u[:,3]==1)))
print("total amount spent by female: ",np.round(a1))
print("total amount spent by male: ",np.round(a2))

total amount spent by female:  1571.0
total amount spent by male:  3257.0


In [13]:
#7) what is the min and max tip given
np.max(u[:,2])

10.0

In [14]:
np.min(u[:,2])

1.0

In [18]:
#8 how many male and female are going for dinner and lunch
a1=np.unique(u[:,3].take(np.where((u[:,6]==1))),return_counts=True)      
x,a=a1
a2=np.unique(u[:,3].take(np.where((u[:,6]==0))),return_counts=True)      
w,b=a2
for i in x:
    if(i==0):
        print("total female going for lunch:",a[0])
        print("total female going for dinner:",b[0])
    else:
        print("total male going for lunch:",a[1])
        print("total female going for dinner:",b[1])

total female going for lunch: 35
total female going for dinner: 52
total male going for lunch: 33
total female going for dinner: 124


In [19]:
#9 find out the average size
np.mean(u[:,7])

2.569672131147541

In [21]:
#10 find how many female smokers and male smokers are there
x1=np.unique(u[:,3].take(np.where(u[:,4]==1)),return_counts=True)
a,b=x1
for i in a:
    if (i==0):
        print("Female smokers : ",b[0])
    else:
        print("Male smokers : ",b[1])

Female smokers :  33
Male smokers :  60


In [22]:
x=np.genfromtxt(r"C:\Users\DELL\Downloads\train_extended.csv",delimiter=",",skip_header=1)

In [23]:
import numpy as np

In [27]:
x

array([[ 1.575     ,  1.225     ,  0.375     , ...,  6.3219385 ,
         9.63883   , 10.        ],
       [ 1.2375    ,  1.        ,  0.375     , ...,  3.798833  ,
         7.654365  , 19.        ],
       [ 1.45      ,  1.1625    ,  0.4125    , ...,  7.01650125,
         7.257472  , 11.        ],
       ...,
       [ 1.125     ,  0.9125    ,  0.2875    , ...,  1.984465  ,
         3.118445  ,  7.        ],
       [ 1.625     ,  1.275     ,  0.4125    , ...,  7.86698625,
        10.489315  , 11.        ],
       [ 1.5875    ,  1.25      ,  0.3875    , ...,  7.38504475,
         8.788345  , 11.        ]])

In [29]:
# 1 what is the max and min length
np.max(x[:,0])

7.58349125

In [30]:
np.max(x[:,0])

0.0

In [35]:
# 2 find out the difference between the max and min
np.max(x[:,0])-np.min(x[:,0])

7.58349125

In [36]:
# 3 find out the coloumnwise avgerage
np.mean(x,axis=0)

array([ 1.31244808,  1.02032036,  0.34602787, 23.12343631,  9.98937025,
        4.99318096,  6.63422915,  9.950615  ])

In [38]:
#4 find out all the age whose height is gereater than 0.4

z=x[:,7].take(np.where(y[:,2]>0.4))

In [39]:
z

array([[10., 19., 11.,  9.,  8., 10., 14., 13.,  9., 10., 10.,  6.,  9.,
         7., 14., 16., 19.,  9.,  9.,  9., 12.,  6., 13.,  9.,  9., 11.,
         9.,  8., 10.,  9., 20., 11., 17.,  8.,  5.,  9.,  8.,  5., 15.,
         7., 12., 11.,  8., 11., 12.,  8.,  9., 14., 15.,  9.,  5.,  8.,
        11.,  5., 11.,  8., 13., 11.,  9., 11.,  7.,  7.,  8., 10., 11.,
         9., 13.,  8.,  7.,  7., 10.,  9.,  6.,  4.,  8., 10., 10., 10.,
        10.,  8., 10.,  8.,  8., 10.,  9., 11.,  9.,  7., 13.,  9.,  6.,
        12., 14., 11.,  9., 11., 10.,  8., 11., 15., 10.,  8.,  9.,  5.,
         8.,  9., 11., 11.,  8., 12.,  8., 10.,  7.,  8., 10., 12., 10.,
        13.,  9., 10., 10.,  4.,  6.,  7.,  9.,  4., 10., 16., 10.,  7.,
        14.,  6., 10., 10.,  8., 11., 12.,  9., 11., 17., 10.,  4.,  8.,
        15.,  6., 10.,  7., 10., 11.,  6., 14.,  6., 11., 11., 12.,  3.,
        10.,  7., 10., 11., 11., 13.,  8.,  8.,  8., 10., 16., 11., 11.,
        12., 10.,  6.,  9.,  7., 22., 11., 14., 11.

In [ ]:
#5 what is the average height and weight of the persons whose age is greater than 10.


In [40]:
#6 what is the shell weight
np.sum(x[:,6])

1326845.8295214002

In [42]:
#7  how many persons belongs to each and every unique 

np.unique(x[:,7],return_counts=True)

(array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
        14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26.,
        27., 29.]),
 array([   46,    42,   625,  2787,  5475, 12450, 18276, 26818, 32906,
        30803, 23457, 12717, 10037,  6352,  4831,  3191,  2705,  1953,
         1591,  1206,   721,   296,   352,   110,    51,    46,    99,
           57], dtype=int64))

In [ ]:
#8  what is the difference between shucked weight and viscera weight



In [ ]:
#9 what is the average height of the persons whose age is between 14 and 19.



In [ ]:
#10 what is the average weight if we include all shucked weight ,viscera weight and shell weight with weight.